name: crypto_view
description: "Dashboard de criptos monedas usando el api de binance"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  provider: ^6.1.2
  google_nav_bar: ^5.0.6
  url_launcher: ^6.2.5
  animated_splash_screen: ^1.3.0
  lottie: ^3.1.0
  http: ^1.2.1
  fluttertoast: ^8.2.5
  flutter_secure_storage: ^4.2.1
  flutter_charts: ^0.5.2
  fl_chart: ^0.67.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/animations/
    - assets/icons/
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
